default_stages: [commit]

exclude: (.*\.patch)

repos:
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 5.1.0.1
    hooks:
      - id: buildifier
        files: &bazel_files ^(.*/)?(\w+\.BUILD.bazel|BUILD\.bazel|BUILD|WORKSPACE)$|\.BUILD$|\.bzl$
        args: &bazel_args ["--warnings=native-cc,native-py"]
      - id: buildifier-lint
        files: *bazel_files
        args: *bazel_args
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: double-quote-string-fixer
        types: [python]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: [-i, --style, .style.yapf]
